spring:
  main:
    #配置使用自定义的log
    banner-mode: log
  #配置访问页面路径的前后缀
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  #配置阿里巴巴数据源的四大件
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/k9503?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root

server:
  #配置服务器的访问端口号
  port: 8080

logging:
  level:
    org:
      #日志信息的打印
      springframework: error
    cn:
      com:
        djin:
          springboot:
            mapper: DEBUG

#配置mybatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml



